service: bookshopservicever2
# app and org for use with dashboard.serverless.com
app: bookshopver2
org: saika-m

frameworkVersion: "2"

provider:
  name: aws
  runtime: java8
  httpApi:
    cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource:
          - { "Fn::GetAtt": ["BookshopBooks", "Arn"] }
plugins:
  - serverless-offline
package:
  artifact: build/distributions/hello.zip

functions:
  hello:
    handler: com.serverless.Handler
  createBook:
    handler: com.serverless.CreateBookHandler
    events:
      - http:
          path: /book
          method: post
          cors: true
  getBook:
    handler: com.serverless.GetBookHandler
    events:
      - http:
          path: /book
          method: get
          cors: true
  deleteBook:
    handler: com.serverless.DeleteBookHandler
    events:
      - http:
          path: /book/{id}
          method: delete
          cors: true
  updateBook:
    handler: com.serverless.UpdateBookHandler
    events:
      - http:
          path: /book
          method: put
          cors: true

resources:
  Resources:
    BookshopBooks:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Bookshop-Books
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
